TaxiBookingServiceUI/TaxiBookingServiceUI/Controllers/AreaController.cs
namespace TaxiBookingServiceUI.Controllers
{
    public class AreaController : Controller
    {
        private readonly HelperAPI _api = new HelperAPI();
        private readonly GetStringList getName = new GetStringList();
        public async Task<ActionResult> Display()
        {
            try
            {
                List<AreaViewModel> users = new List<AreaViewModel>();
                HttpResponseMessage res = await _api.GetAsync(ApiUrls.AreaDisplay, 0);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    users = JsonConvert.DeserializeObject<List<AreaViewModel>>(result);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
                return View(users);
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public ActionResult Add()
        {
            ViewBag.States = getName.GetStates();
            return View();
        }

        [HttpPost]
        public ActionResult Add(AreaModel areaModel)
        {
            try
            {
                ViewBag.States = getName.GetStates();
                areaModel.UserEmail = HttpContext.Session.GetString("_adminEmail");
                string token = HttpContext.Session.GetString("_admintoken");
                HttpResponseMessage res = _api.PostAsync(areaModel, ApiUrls.AreaAdd, token);

                if (res.IsSuccessStatusCode)
                {
                    TempData["msg"] = "Area Added Successfully";
                    return RedirectToAction("Display");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                ViewBag.States = getName.GetStates();
                AreaViewModel area = new AreaViewModel();
                HttpResponseMessage res = await _api.GetAsync(ApiUrls.AreaSearch, id);

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    area = JsonConvert.DeserializeObject<AreaViewModel>(result);

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
                return View(area);
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, AreaModel areaModel)
        {
            try
            {
                ViewBag.States = getName.GetStates();
                areaModel.UserEmail = HttpContext.Session.GetString("_adminEmail");
                string token = HttpContext.Session.GetString("_admintoken");
                HttpResponseMessage res = _api.PutAsync(ApiUrls.AreaUpdate, areaModel, id, token);

                if (res.IsSuccessStatusCode)
                {
                    TempData["msg"] = "Area Updated Successfully";
                    return RedirectToAction("Display");
                }
                else
                {
                    TempData["errmsg"] = "You are currently unauthorized";
                    return RedirectToAction("Display");
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                string token = HttpContext.Session.GetString("_admintoken");
                HttpResponseMessage res = await _api.DeleteAsync(ApiUrls.AreaDelete, id, token);

                if (res.IsSuccessStatusCode)
                {
                    TempData["msg"] = "Area Deleted Successfully";
                    return RedirectToAction("Display");
                }
                else
                {
                    TempData["errmsg"] = "You are currently unauthorized";
                    return RedirectToAction("Display");
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }
    }
}

TaxiBookingServiceUI/TaxiBookingServiceUI/Controllers/UserController.cs
namespace TaxiBookingServiceUI.Controllers
{
    public class UserController : Controller
    {
        private readonly HelperAPI _api = new HelperAPI();

        public const string SessionUserToken = "_usertoken";

        public const string SessionUserEmail = "_userEmail";

        public readonly IHttpContextAccessor _httpContext;

        public UserController(IHttpContextAccessor httpContext)
        {
            _httpContext = httpContext;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Profile()
        {
            UserViewModel user = new UserViewModel();
            string _email = HttpContext.Session.GetString("_userEmail");

            HttpResponseMessage res = await _api.GetByStringAsync(ApiUrls.UserSearch, _email, null);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                user = JsonConvert.DeserializeObject<UserViewModel>(result);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
            }
            return View(user);

        }

        public async Task<ActionResult> Edit()
        {
            UserEditModel user = new UserEditModel();
            string email = HttpContext.Session.GetString("_userEmail");

            HttpResponseMessage res = await _api.GetByStringAsync(ApiUrls.UserSearch, email, null);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                user = JsonConvert.DeserializeObject<UserEditModel>(result);

            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
            }


            return View(user);

        }

        [HttpPost]
        public ActionResult Edit(string email, UserEditModel userEdit)
        {
            if (ModelState.IsValid)
            {
                string token = HttpContext.Session.GetString("_usertoken");

                var result = _api.PutByStringAsync(ApiUrls.UserUpdate, userEdit, email, token);

                if (result.IsSuccessStatusCode)
                {
                    TempData["msg"] = "User Updated Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errmsg"] = "You are currently unauthorized";
                    return RedirectToAction("Index");
                }
            }
            return View();

        }

        public async Task<ActionResult> Display()
        {
            List<UserViewModel> users = new List<UserViewModel>();
            HttpResponseMessage res = await _api.GetAsync(ApiUrls.UserDisplay, 0);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                users = JsonConvert.DeserializeObject<List<UserViewModel>>(result);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
            }
            return View(users);
        }

        public ActionResult Add()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Add(UserModel userModel)
        {
            using (HttpClient client = _api.Initial())
            {
                userModel.RoleName = Roles.User.ToString();
                if (ModelState.IsValid)
                {
                   var result = _api.PostAsync(userModel, ApiUrls.UserAdd, null);

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Please enter your email and password to login";
                        return RedirectToAction("Login");
                    }
                    else
                    {
                        return View();
                    }
                }
                TempData["errmsg"] = "User could not be added";
                return View();
            }
        }

        public IActionResult Login()
        {
            HttpContext.Session.Remove(SessionUserToken);
            HttpContext.Session.Remove(SessionUserEmail);
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel login)
        {
            var result = _api.Login(login, ApiUrls.Login);

            if (result.IsSuccessStatusCode)
            {
                var res = result.Content.ReadAsStringAsync().Result;
                HttpContext.Session.SetString(SessionUserToken, res);
                HttpContext.Session.SetString(SessionUserEmail, login.Email);
                return RedirectToAction("Index", "Booking");
            }
            else
            {
                TempData["errmsg"] = "Wrong Email or Password entered";
                return View();
            }

        }
    }
}

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Shared/UnAuthorized.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "401-UNAUTHROIZED";
    Layout = null;

    ViewBag.UserToken = HttpContextAccessor.HttpContext.Session.GetString("_usertoken");
    ViewBag.AdminToken = HttpContextAccessor.HttpContext.Session.GetString("_admintoken");
    ViewBag.Token = HttpContextAccessor.HttpContext.Session.GetString("_drivertoken");


}

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<style>
    body {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);
    }

    .error-template {
        padding: 40px 15px;
        text-align: center;
    }

    .error-actions {
        margin-top: 15px;
        margin-bottom: 15px;
    }

        .error-actions .btn {
            margin-right: 10px;
        }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!
                </h1>
                <h2>
                    401 Authorized
                </h2>
                <div class="error-details">
                    Sorry, an error has occured, You are not authorized to see the Requested page!
                </div>
                <div class="error-actions">
                   @* @if(ViewBag.Token == null && ViewBag.AdminToken == null)
                    {
                        <a asp-action="Index" asp-controller="User" class="btn btn-primary btn-lg">
                            <span class="glyphicon glyphicon-home"></span>
                            Take Me tO User
                        </a>
                    }
                    @if (ViewBag.UserToken == null && ViewBag.Token == null)
                    {
                        <a asp-action="Services" asp-controller="Admin" class="btn btn-primary btn-lg">
                            <span class="glyphicon glyphicon-home"></span>
                            Take Me to Admin
                        </a>
                    }
                    @if (ViewBag.UserToken == null && ViewBag.AdminToken == null)
                    {
                        <a asp-action="DriverLocation" asp-controller="Driver" class="btn btn-primary btn-lg">
                            <span class="glyphicon glyphicon-home"></span>
                            Take Me to Driver
                        </a>
                    }*@
                    @*<a asp-action="Login" asp-controller="User" class="btn btn-primary btn-lg">
                        <span class="glyphicon glyphicon-home"></span>
                        Log Out
                    </a>*@
                </div>
            </div>
        </div>
    </div>
</div>

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Shared/_DriverLayout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


@{
    ViewBag.Token = HttpContextAccessor.HttpContext.Session.GetString("_drivertoken");
    if(ViewBag.Token == null)
    {
            { await Html.RenderPartialAsync("UnAuthorized.cshtml"); }

            <main role="main" class="pb-3">
                @{
                    IgnoreBody();
                }
            </main>
        
    }  
    else
    {

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaxiBookingServiceUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
</head>


<body>
    <header class="navigation">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3">
            <div class="container-fluid">.
                <a class="navbar-brand" asp-area="" asp-controller="Driver" asp-action="Index">TaxiBookingService</a>
                <div class="navigation navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="padding: 8px">
                            <button onclick="@("window.location.href='" + @Url.Action("Display", "VehicleDetail") + "'");" class="dropbtn">Vehicle</button>
                        </li>
                        <li class="nav-item" style="padding: 8px">
                            <button onclick="@("window.location.href='" + @Url.Action("GetRequest", "Driver") + "'");" class="dropbtn">Accept Rides</button>
                        </li>
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="dropbtn" style="margin-right: 50px">Profile</button>
                    <div class="dropdown-content">
                        <a class="text-dark" asp-area="" asp-controller="Driver" asp-action="Profile">Visit Profile</a>
                        <a class="text-dark" asp-area="" asp-controller="Driver" asp-action="Login">Log Out</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaxiBookingService
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
}
}

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


@{
    ViewBag.Token = HttpContextAccessor.HttpContext.Session.GetString("_admintoken");
    if(ViewBag.Token == null)
    {
            { await Html.RenderPartialAsync("UnAuthorized.cshtml"); }

            <main role="main" class="pb-3">
                @{
                    IgnoreBody();
                }
            </main>
        
    }  
    else
    {


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaxiBookingServiceUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
</head>


<body>
    <header class="navigation">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">TaxiBookingService</a>
                <div class="navigation navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item" style="padding: 8px">
                            <div class="dropdown">
                                <button class="dropbtn">Locations</button>
                                <div class="dropdown-content">
                                    <a class="text-dark" asp-area="" asp-controller="Area" asp-action="Display">Display</a>
                                    <a class="text-dark" asp-area="" asp-controller="Area" asp-action="Add">Add</a>
                                </div>
                            </div>
                        </li>
                                <li class="nav-item" style="padding: 8px">
                            <div class="dropdown">
                                <button class="dropbtn">Cancellation Reasons</button>
                                <div class="dropdown-content">
                                    <a class="text-dark" asp-area="" asp-controller="CancellationReason" asp-action="Display">Display</a>
                                    <a class="text-dark" asp-area="" asp-controller="CancellationReason" asp-action="Add">Add</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item" style="padding: 8px">
                            <button onclick="@("window.location.href='" + @Url.Action("Display", "Admin") + "'");" class="dropbtn">Drivers</button>
                        </li>
                    </ul>
                </div>
                <button onclick="@("window.location.href='" + @Url.Action("Login", "Admin") + "'");" class="dropbtn">Log Out</button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaxiBookingService
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
}
}

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaxiBookingServiceUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaxiBookingServiceUI.StyleSheet.css" asp-append-version="true" />
</head>


<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">TaxiBookingService</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaxiBookingServiceUI
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Shared/_UserLayout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


@{
    ViewBag.UserToken = HttpContextAccessor.HttpContext.Session.GetString("_usertoken");
    if (ViewBag.UserToken == null)
    {
            { await Html.RenderPartialAsync("UnAuthorized.cshtml"); }

            <main role="main" class="pb-3">
                @{
                    IgnoreBody();
                }
            </main>
        
    }  
    else
    {


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaxiBookingServiceUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
</head>


<body>
    <header class="navigation">
        <nav class="navigation navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Driver" asp-action="Index">TaxiBookingService</a>
                <div class="navigation navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <button onclick="@("window.location.href='" + @Url.Action("UserBooking", "Booking") + "'");" class="dropbtn">Book Ride</button>
                        </li>
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="dropbtn" style="margin-right: 50px">Profile</button>
                    <div class="dropdown-content">
                        <a class="text-dark" asp-area="" asp-controller="User" asp-action="Profile">Visit Profile</a>
                        <a class="text-dark" asp-area="" asp-controller="User" asp-action="Login">Log Out</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaxiBookingServiceUI
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
}
}