TaxiBookingServiceUI/TaxiBookingServiceUI/ViewModels/DriverViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TaxiBookingServiceUI.Models
{
    public class DriverViewModel
    {
        [Required]
        [StringLength(20)]
        [DisplayName("First Name")]
        [RegularExpression(@"^[A-za-z]*((-|\s)*[A-Za-z])*$", ErrorMessage = "Not a valid Name")]
        public string FirstName { get; set; }

        [Required]
        [DisplayName("Last Name")]
        [StringLength(20)]
        [RegularExpression(@"^[A-za-z]*((-|\s)*[A-Za-z])*$", ErrorMessage = "Not a valid Name")]
        public string LastName { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Email cannot be more than 30")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered phone format is not valid.")]
        public string PhoneNumber { get; set; }

        [Required]
        public string Gender { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayName("Date of Birth")]
        public DateTime DateOfBirth { get; set; }

        [Required]
        [StringLength(8)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string RoleName { get; set; }

        [Required]
        [DisplayName("Driving License")]
        [StringLength(15)]
        public string DrivingLicense { get; set; }

        [DataType(DataType.Currency)]
        [Range(0, int.MaxValue)]
        public decimal Wallet { get; set; }
        public decimal Rating { get; set; }

        [Required]
        public bool IsApproved { get; set; }
    }
}

TaxiBookingServiceUI/TaxiBookingServiceUI/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TaxiBookingServiceUI.Models
{
    public class LoginViewModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        [StringLength(20, ErrorMessage = "Email cannot be more than 20")]
        public string Email { get; set; }

        [Required]
        [StringLength(8)]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

TaxiBookingServiceUI/TaxiBookingServiceUI/Controllers/DriverController.cs
using TaxiBookingServiceUI.DTOModels;

namespace TaxiBookingServiceUI.Controllers
{
    public class DriverController : Controller
    {
        private readonly HelperAPI _api = new HelperAPI();
        private readonly GetStringList getName = new GetStringList();
        private readonly BookingService bookingService = new BookingService();

        public const string SessionDriverToken = "_drivertoken";

        public const string SessionDriverEmail = "_driverEmail";

        public readonly IHttpContextAccessor _httpContext;

        public DriverController(IHttpContextAccessor httpContext)
        {
            _httpContext = httpContext;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Profile()
        {
            try
            {
                DriverViewModel drivers = new DriverViewModel();

                string driverEmail = HttpContext.Session.GetString("_driverEmail");

                HttpResponseMessage res = await _api.GetByStringAsync(ApiUrls.DriverSearch, driverEmail, null);

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    drivers = JsonConvert.DeserializeObject<DriverViewModel>(result);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
                return View(drivers);
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public ActionResult Add()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Add(DriverViewModel driverView)
        {
            try
            {
                if (driverView.PhoneNumber.Length > 10) return View();

                driverView.RoleName = Roles.Driver.ToString();
                if (ModelState.IsValid)
                {
                    var result = _api.PostAsync(driverView, ApiUrls.DriverAdd, null);

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Please Login using your email and password";
                        return RedirectToAction("Login");
                    }
                    else
                    {
                        return View();
                    }
                }
                TempData["errmsg"] = "Please check your entries again";
                return View();
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public IActionResult Login()
        {
            HttpContext.Session.Remove(SessionDriverEmail);
            HttpContext.Session.Remove(SessionDriverToken);
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel login)
        {
            try
            {
                var result = _api.Login(login, ApiUrls.Login);

                if (result.IsSuccessStatusCode)
                {
                    var res = result.Content.ReadAsStringAsync().Result;
                    HttpContext.Session.SetString(SessionDriverToken, res);
                    HttpContext.Session.SetString(SessionDriverEmail, login.Email);
                    return RedirectToAction("DriverLocation", "Location");
                }
                else
                {
                    TempData["errmsg"] = "Wrong Email or Password entered";
                    return View();
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public async Task<ActionResult> GetRequest()
        {
            try
            {
                if (HttpContext.Session.GetString("_driverLocation") != "true")
                {
                    return RedirectToAction("DriverLocation", "Location");
                }

                BookingRequest bookings = new BookingRequest();

                string email = HttpContext.Session.GetString("_driverEmail");

                HttpResponseMessage res = await _api.GetByStringAsync(ApiUrls.BookingRequest, email, null);

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    bookings = JsonConvert.DeserializeObject<BookingRequest>(result);
                }
                else if(res.StatusCode == System.Net.HttpStatusCode.NotFound)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }

                return View(bookings);
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public ActionResult AcceptRequest(int id)
        {
            try
            {
                BookingViewModel booking = new BookingViewModel();
                string driverEmail = HttpContext.Session.GetString("_driverEmail");
                string token = HttpContext.Session.GetString("_drivertoken");
                using (HttpClient client = _api.Initial())
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: token);
                    var message = new HttpRequestMessage(HttpMethod.Put, $"api/Booking/AcceptRequest/{id}/{driverEmail}");
                    var postTask = client.SendAsync(message);
                    postTask.Wait();

                    var res = postTask.Result;

                    if (res.IsSuccessStatusCode)
                    {
                        var result = res.Content.ReadAsStringAsync().Result;
                        booking = JsonConvert.DeserializeObject<BookingViewModel>(result);

                    }
                    else
                    {
                        TempData["errmsg"] = "You are not approved by the Admin yet, please wait";
                        return RedirectToAction("GetRequest");
                    }
                    TempData["msg"] = "Your Ride has started";
                    return RedirectToAction("CurrentRide", new { id = id });
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public  ActionResult CompleteRide(int id)
        {
            try
            {
                BookingViewModel booking = new BookingViewModel();
                string token = HttpContext.Session.GetString("_drivertoken");
                using (HttpClient client = _api.Initial())
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(scheme: "Bearer", parameter: token);

                    var message = new HttpRequestMessage(HttpMethod.Put, $"api/Booking/CompleteRide/{id}");
                    var postTask = client.SendAsync(message);
                    postTask.Wait();

                    var res = postTask.Result;

                    if (res.IsSuccessStatusCode)
                    {
                        var result = res.Content.ReadAsStringAsync().Result;
                        booking = JsonConvert.DeserializeObject<BookingViewModel>(result);

                        if(String.Equals(booking.PaymentMode, "Wallet"))
                        {
                            bookingService.VerifyWalletPayment(booking.Id, token, true, "Wallet", null); 
                            HttpContext.Session.SetString("_driverLocation", "false");
                            TempData["msg"] = "Please provide a rating for the driver";
                            return RedirectToAction("Rating", new { id = id });
                        }
                        else
                        {
                            TempData["msg"] = "Please verify the payment details, for your convinience";
                            return RedirectToAction("CurrentRide", new { id =booking.Id });
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                    }

                    return View();
                }
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }

        public async Task<ActionResult> CurrentRide(int id)
        {
            ViewBag.PaymentModes = getName.GetPaymentModes();

            BookingViewModel bookingViewModel = new BookingViewModel();
            HttpResponseMessage res = await _api.GetAsync(ApiUrls.BookingSearch, id);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                bookingViewModel = JsonConvert.DeserializeObject<BookingViewModel>(result);
            }
            else
            {
                TempData["errmsg"] = "A error has occured in accepting the request. Please try again";
                return RedirectToAction("Index");
            }
            if(bookingViewModel.Status == "Declined")
            {
                TempData["errmsg"] = "User delined the ride, please check your history to see the reason";
                return RedirectToAction("GetRequest");
            }
            return View(bookingViewModel);
        }

        public ActionResult ReachedLocation(int id, string Otp)
        {
            string token = HttpContext.Session.GetString("_drivertoken");

            string otp = TempData["Otp"].ToString();

TaxiBookingServiceUI/TaxiBookingServiceUI/Controllers/UserController.cs
namespace TaxiBookingServiceUI.Controllers
{
    public class UserController : Controller
    {
        private readonly HelperAPI _api = new HelperAPI();

        public const string SessionUserToken = "_usertoken";

        public const string SessionUserEmail = "_userEmail";

        public readonly IHttpContextAccessor _httpContext;

        public UserController(IHttpContextAccessor httpContext)
        {
            _httpContext = httpContext;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Profile()
        {
            UserViewModel user = new UserViewModel();
            string _email = HttpContext.Session.GetString("_userEmail");

            HttpResponseMessage res = await _api.GetByStringAsync(ApiUrls.UserSearch, _email, null);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                user = JsonConvert.DeserializeObject<UserViewModel>(result);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
            }
            return View(user);

        }

        public async Task<ActionResult> Edit()
        {
            UserEditModel user = new UserEditModel();
            string email = HttpContext.Session.GetString("_userEmail");

            HttpResponseMessage res = await _api.GetByStringAsync(ApiUrls.UserSearch, email, null);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                user = JsonConvert.DeserializeObject<UserEditModel>(result);

            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
            }


            return View(user);

        }

        [HttpPost]
        public ActionResult Edit(string email, UserEditModel userEdit)
        {
            if (ModelState.IsValid)
            {
                string token = HttpContext.Session.GetString("_usertoken");

                var result = _api.PutByStringAsync(ApiUrls.UserUpdate, userEdit, email, token);

                if (result.IsSuccessStatusCode)
                {
                    TempData["msg"] = "User Updated Successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errmsg"] = "You are currently unauthorized";
                    return RedirectToAction("Index");
                }
            }
            return View();

        }

        public async Task<ActionResult> Display()
        {
            List<UserViewModel> users = new List<UserViewModel>();
            HttpResponseMessage res = await _api.GetAsync(ApiUrls.UserDisplay, 0);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                users = JsonConvert.DeserializeObject<List<UserViewModel>>(result);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
            }
            return View(users);
        }

        public ActionResult Add()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Add(UserModel userModel)
        {
            using (HttpClient client = _api.Initial())
            {
                userModel.RoleName = Roles.User.ToString();
                if (ModelState.IsValid)
                {
                   var result = _api.PostAsync(userModel, ApiUrls.UserAdd, null);

                    if (result.IsSuccessStatusCode)
                    {
                        TempData["msg"] = "Please enter your email and password to login";
                        return RedirectToAction("Login");
                    }
                    else
                    {
                        return View();
                    }
                }
                TempData["errmsg"] = "User could not be added";
                return View();
            }
        }

        public IActionResult Login()
        {
            HttpContext.Session.Remove(SessionUserToken);
            HttpContext.Session.Remove(SessionUserEmail);
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel login)
        {
            var result = _api.Login(login, ApiUrls.Login);

            if (result.IsSuccessStatusCode)
            {
                var res = result.Content.ReadAsStringAsync().Result;
                HttpContext.Session.SetString(SessionUserToken, res);
                HttpContext.Session.SetString(SessionUserEmail, login.Email);
                return RedirectToAction("Index", "Booking");
            }
            else
            {
                TempData["errmsg"] = "Wrong Email or Password entered";
                return View();
            }

        }
    }
}

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Driver/Add.cshtml
@model TaxiBookingServiceUI.Models.DriverViewModel

@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<h5>Add</h5>

<hr />

<strong style="color: red">@TempData["errmsg"]</strong>
<strong style="color: green">@TempData["msg"]</strong>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" type="number"/>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
             @*   <input asp-for="Gender" class="form-control" />*@
                Male
                @Html.RadioButtonFor(model => model.Gender, "Male")
                Female
                @Html.RadioButtonFor(model => model.Gender, "Female")
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DrivingLicense" class="control-label"></label>
                <input asp-for="DrivingLicense" class="form-control" />
                <span asp-validation-for="DrivingLicense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Login" asp-controller="User">Login As User</a>
    <a asp-action="Login" asp-controller="Admin">Login As Admin</a>
</div>

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Driver/CurrentRide.cshtml
@model TaxiBookingServiceUI.Models.BookingViewModel

@{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    ViewData["Title"] = "CurrentRide";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}
<script>
    $(document).ready(function () {
        console.log("change");
        $('#Verify').change(function () {
            var selectionval = (this.value);
            console.log(selectionval)
            if(selectionval == "False") {
                document.getElementById("Remark").style.display = "block";
            }
            else {
                document.getElementById("Remark").style.display = "none";
            }
        });
    });
</script>

<body>
<h5>Current Ride</h5>

<strong style="color: red">@TempData["errmsg"]</strong>
<strong style="color: green">@TempData["msg"]</strong>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PickupLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PickupLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PickupTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PickupTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DropTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DropTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DropLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DropLocation)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentMode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentMode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Payment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Payment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehiclePreference)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehiclePreference)
        </dd>
    </dl>
</div>
<div>

            @{
            ViewBag.Status = Model.Status;

            if(ViewBag.Status == Statuses.Accepted.ToString())
            {
                <br />


                @using (Html.BeginForm("ReachedLocation", "Driver", FormMethod.Post, new { id = Model.Id}))
                {
                    @Html.HiddenFor(model => model.Id)
                    <strong>Enter the OTP given by the user? </strong>
                    <input type="number" id="Otp" name="Otp" class="form-control"/>
                    <br />
                    <input type="submit" value="Verify" />
                }
            }
            if(ViewBag.Status == Statuses.Arrived.ToString())
            {
                <br />
                @Html.ActionLink("Ride Completed", "CompleteRide", new {id = Model.Id})
            }
            if(ViewBag.Status == Statuses.Completed.ToString())
            {
                @using (Html.BeginForm("PaymentVerfied", "Driver" , FormMethod.Post, new { id = Model.Id, Verify = Model.Verify }))
                {
                    <strong>Payment Mode? </strong>
                    @Html.HiddenFor(model => model.Id)


                    <label asp-for="PaymentMode" class="control-label required"></label>
                    @Html.DropDownList("PaymentMode", new List<SelectListItem>() { new SelectListItem() { Text = "Cash", Value = "Cash" }, new SelectListItem() { Text = "UPI", Value = "UPI" } }, "--Payment Mode--", new {@id="PaymentMode", @class="form-control"})

                    <strong>Verify that the payment has been done? </strong>
                    @Html.DropDownListFor(model => model.Verify, new List<SelectListItem>() { new SelectListItem() { Text = "Yes", Value = "True" }, new SelectListItem() { Text = "No", Value = "False" } }, "Verify", htmlAttributes: new {@id="Verify", @class = "form-control"})
                    <br />
                    
                    <div id="Remark" style="display: none">
                        <label id="Remark" class="control-label">Remark</label>
                        <input type="text" id="Remark" name="Remark" class="form-control"/>
                    </div>

                    <input type="submit" value="Verify" />
                }
            }
        }
</div>
</body>

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Driver/GetRequest.cshtml
@model TaxiBookingServiceUI.Models.BookingRequest

@{
    ViewData["Title"] = "GetRequest";
    Layout = "~/Views/Shared/_DriverLayout.cshtml";
}

<h4>Booking Request</h4>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PickupLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PickupLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DropLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DropLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PickupTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PickupTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Payment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Payment)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Accept Request", "AcceptRequest", new {id = Model.Id}) |
    @Html.ActionLink("Decline Request", "Index")
</div>

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Driver/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DriverLayout.cshtml";
}

<h5>Index</h5>


<strong style="color: red">@TempData["errmsg"]</strong>
<strong style="color: green">@TempData["msg"]</strong>

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Driver/Login.cshtml
@model TaxiBookingServiceUI.Models.LoginViewModel

@{
    ViewData["Title"] = "Driver Login";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<h5>Driver Login</h5>

<hr />

<strong style="color: red">@TempData["errmsg"]</strong>
<strong style="color: green">@TempData["msg"]</strong>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Login" asp-controller="User">Login As User</a>
    <a asp-action="Login" asp-controller="Admin">Login As Admin</a>
</div>

<div>
    <a asp-action="Add" asp-controller="Driver">Register As Driver</a>
</div>

TaxiBookingServiceUI/TaxiBookingServiceUI/Views/Driver/Profile.cshtml
@model TaxiBookingServiceUI.Models.DriverViewModel

@{
    ViewData["Title"] = "Profile";
    Layout = "~/Views/Shared/_DriverLayout.cshtml";
}

<h5>Profile</h5>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DrivingLicense)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DrivingLicense)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Wallet)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Wallet)
        </dd>
    </dl>
</div>